### ISSUE TITLE
Could not execute entrypoint stage 'client' due to errors, provided by 'anvil_fix'!

### ISSUE THREAD

**Issue by BeansBeefBroccoli** [NerdHubMC/AnvilFix#16]
#### What happens:

Game does not launch

#### What you expected to happen:

Game to launch

#### Steps to reproduce:

1. Click "Launch"

2. Wait

 

#### Affected Versions:

- Anvil Fix: 1.1.2

- Minecraft: 1.14.4

- Fabric Loader: 0.11.1

- Fabric API (if present): 0.284+1.14

#### Possibly Conflicting Mods (Provide their version, as well):

???

#### Additional Information and Log:

I am using MultiMC

https://paste.ee/p/zR9l4

**Comment by BeansBeefBroccoli** [comment]
this does not matter anymore because I am not playing that modpack anymore but please try to fix this.

**Comment by UpcraftLP** [comment]
You're actually using 1.1.1, not 1.1.2. Issue should be fixed by correcting that.

**Comment by BeansBeefBroccoli** [comment]
ok thank you
