### ISSUE TITLE
[1.16.4] Server load fails

### ISSUE THREAD

**Issue by JuergenSchT** [NerdHubMC/AnvilFix#17]
#### Issue Description:
After updating AnvilFix to the latest version, the server fails to load. The client appears to work fine. AnvilFix 1.1.3 also works fine on the server.
#### What happens:
A few seconds after sending the server start command, the load is interrupted after Mesh prints a message.
No crash report is generated, so [here's the server log](https://pastebin.com/ec4MMYNr).
#### What you expected to happen:
The server to load properly. Or to crash.
#### Steps to reproduce:
1. Create a 1.16.4 server with Fabric API and AnvilFix
2. Try to run it.
#### Affected Versions (Do *not* use "latest"):
- Anvil Fix: 1.2.0
- Minecraft: 1.16.4
- Fabric Loader: 0.11.1
- Fabric API (if present): 0.29.3

**Comment by UpcraftLP** [comment]
fixed in 307629f
