### ISSUE TITLE
Conflict with Sodium?

### ISSUE THREAD

**Issue by sldains** [NerdHubMC/AnvilFix#18]
#### Issue Description:
Using Anvil Fix and Sodium together causes issues.

#### What happens:
If I have both this and Sodium loaded then all the entities (including the player) disappear and I get constant "OpenGL debug message, id=1283" messages in my log.  This only happens when loading an existing save.

#### Steps to reproduce:

1. Open an existing save. 
2. Not be able to see anything that moves.

____
#### Affected Versions (Do *not* use "latest"):

- Anvil Fix: 1.2.1
- Minecraft: 1.16.5
- Fabric Loader: 0.11.1
- Fabric API (if present): 0.31

#### Possibly Conflicting Mods (Provide their version, as well):
- Sodium: 0.1

**Comment by sldains** [comment]
With further testing, the issue seems to be coming from Better Sodium Video Settings Button (v1.0.2.1), though I still don't understand why that would cause a conflict with your mod.

**Comment by UpcraftLP** [comment]
This is an issue with `Better Sodium Video Settings Button`, and occurs when combined with other mods, too.

Nothing we can do on our end.

**Comment by mrmelon54** [comment]
I know the dev for Better Sodium Video Settings Button so I'll let him know

**Comment by piemanau** [comment]
Hey @sldains can I know what mods you had in your client or provide a crash log? Thank you!
