### ISSUE TITLE
CurseForge description needs to let people know it's Fabric

### ISSUE THREAD

**Issue by ghost** [NerdHubMC/AnvilFix#19]
I'll never find it searching for Fabric mods but I did try and add it to a Forge pack.

**Comment by UpcraftLP** [comment]
Hint: watch for [the category](https://www.curseforge.com/minecraft/mc-mods/fabric) ;)

![image](https://user-images.githubusercontent.com/10714589/111411924-bd7d5700-86db-11eb-98a2-d5d10309c90b.png)

**Comment by markygnlg** [comment]
HAHA!! I just asked this a few minutes ago! I had no idea about the 'Categories' displaying the Fabric thingy!!

I got the same response too!
