### ISSUE TITLE
Could you please mention that this is a FABRIC mod on your description?

### ISSUE THREAD

**Issue by markygnlg** [NerdHubMC/AnvilFix#20]
#### Issue Description:
Could you please mention that this is a FABRIC mod on your description?

Closing my server for this mod is somewhat time consuming - there is no way to know that its a Fabric mod.
![Ol1Tcf8](https://user-images.githubusercontent.com/62978705/115984339-c409c300-a5e5-11eb-94aa-8c8b0004b666.png)

https://i.imgur.com/Ol1Tcf8.png

**Comment by alothmanmoe** [comment]
It is.

![](https://i.imgur.com/D4OETkz.png)

**Comment by UpcraftLP** [comment]
[![image](https://user-images.githubusercontent.com/10714589/115984451-6bb3d080-a5a7-11eb-8e39-34871057a652.png)](https://www.curseforge.com/minecraft/mc-mods/anvil-fix/files/3176763)

**Comment by markygnlg** [comment]
Cool, thx for the 1st screenshot - but you may know that to get to the 2nd screenshot is something most people don't know how to do - hence the regular 'is this mod available for mc version x.xx.1?'

From now on, I'll keep an eye on the 'Categories'

Thx mate.
