### ISSUE TITLE
Update to fabric 1.17

### ISSUE THREAD

**Issue by mrmelon54** [NerdHubMC/AnvilFix#21]
Can you update to fabric 1.17 or provide a branch so I can port the mod?

**Comment by uplime** [comment]
Hello fellow up! +1 we would love this **up**date for our 1.17 server

**Comment by mrmelon54** [comment]
ok I'll try and remember to make a fork and update it

**Comment by NebelNidas** [comment]
Any updates on this, @MrMelon54?

**Comment by mrmelon54** [comment]
nah sorry I completely forgot lol

if I remember I can probably do a 1.17 and 1.18 update but I'd need the dev to upload it to curseforge (or add permission for me to upload there) unless I just create a new project?

**Comment by NebelNidas** [comment]
@UpcraftLP What's your stance on this?

**Comment by UpcraftLP** [comment]
Feel free to make PRs for it (I made respective branches), otherwise I'll do the update myself sometime between christmas and new year

**Comment by mrmelon54** [comment]
Ok I started doing it and I'll do 1.18 after I'm done with 1.17

**Comment by mrmelon54** [comment]
Update for 1.17: #23

**Comment by mrmelon54** [comment]
@UpcraftLP I had some issues with the minecrell licenser when building for 1.18

**Comment by UpcraftLP** [comment]
> @UpcraftLP I had some issues with the minecrell licenser when building for 1.18

it's fine I'll fix those myself

**Comment by mrmelon54** [comment]
Ok I sent a PR for 1.18 as well but it has the licenser issues: #25
