### ISSUE TITLE
1.19 update

### ISSUE THREAD

**Issue by judelahage** [NerdHubMC/AnvilFix#26]
I'm not exactly sure if this is an issue but I just wanted to reach out to the mod devs asking if there is going to be an updated version of this fabric mod for minecraft 1.19 since I've been using it for a while in my 1.18 world but now it no longer works after I updated to 1.19.

**Comment by MattyF4tty** [comment]
I would love to see this as well considering how much it helped in 1.18 it would be great to have it in 1.19.

**Comment by bsasealteam6** [comment]
I made a quick and dirty 1.19 port at https://github.com/bsasealteam6/AnvilFix/releases/tag/1.4.0

**Comment by manuelgrabowski** [comment]
Thanks for the quick port, works like a charm!

**Comment by manuelgrabowski** [comment]
@UpcraftLP Any chance to get the port merged? Used it without issues for a while now, but would love to go back to an "official" version from Modrinth or Curseforge.

**Comment by jacklollz2** [comment]
Considering it's been so long, it's probably abandoned.

**Comment by manuelgrabowski** [comment]
Looks like it, but they're still plenty active on Github, so at least they didn't abandon MC modding in general. I've seen lots of mods come back to live after skipping an entire version, sometimes other things just take priority – totally understandable, especially given that there's a perfectly fine workaround for people who want it bad enough to come to Github issues for answers. Maybe we'll get an official 1.20 version. :)

**Comment by jacklollz2** [comment]
Good to hear

**Comment by manuelgrabowski** [comment]
@bsasealteam6 Any chance you might wanna do a 1.20 port as well? 😅

**Comment by bsasealteam6** [comment]
@manuelgrabowski Updated to 1.20, also put it on curseforge and modrinth at https://curseforge.com/minecraft/mc-mods/anvilfixreborn and https://modrinth.com/mod/anvil-fix-reborn
