### ISSUE TITLE
No config option to disable anvil damage

### ISSUE THREAD

**Issue by IronPiston** [NerdHubMC/AnvilFix#3]
#### What happens:
No option to disable anvil damage in config

#### What you expected to happen:
There should be a config option to disable damage, as suggested by the Curseforge page

#### Steps to reproduce:

1. Open config file
2. 
3. 
...

____
#### Affected Versions (Do *not* use "latest"):

- Anvil Fix: 1.12.2-1.0.1.jar 
- Minecraft: 1.12.2
- Fabric Loader: N/A
- Fabric API (if present): N/A

#### Possibly Conflicting Mods (Provide their version, as well):
No other mods installed

**Comment by UpcraftLP** [comment]
this feature isn't in the 1.12 version yet.
