### ISSUE TITLE
Mod breaks Ender IO Anvil recipes

### ISSUE THREAD

**Issue by calloatti** [NerdHubMC/AnvilFix#4]
#### Issue Description:

When loaded, Ender IO anvil recipes get broken.

#### What happens:

With anvilfix:

![image](https://user-images.githubusercontent.com/12817862/54163401-b27df500-4437-11e9-930c-ab52066ba6dc.png)

#### What you expected to happen:

Without anvilfix

![image](https://user-images.githubusercontent.com/12817862/54163332-5a46f300-4437-11e9-8b86-d9edec079c1c.png)

#### Steps to reproduce:

See screenshots

____
#### Affected Versions (Do *not* use "latest"):

- Anvil Fix: AnvilFix-1.12.2-1.0.1
- Minecraft:  Forge 14.23.5.2768 for Minecraft 1.12.2
- Fabric Loader: 
- Fabric API (if present): 

#### Possibly Conflicting Mods (Provide their version, as well):
- mod1 EnderIO-1.12.2-5.0.40
- mod2 EnderCore-1.12.2-0.5.45

**Comment by LumberWizard** [comment]
This is still happening on the dark steel anvil, and on the vanilla anvil upgrading always costs 1 level, instead of the level set by Ender IO.

Forge version: 14.23.5.2836
AnvilFix version: 1.0.3
EnderCore version: 0.5.57
Ender IO version: 5.0.43
