### ISSUE TITLE
Ignore incremental repair cost not working properly

### ISSUE THREAD

**Issue by diogohd8** [NerdHubMC/AnvilFix#7]
Issue Description: Cumulative xp cost keeps increasing, despite ignore_incremental_repair_cost being set to true.

What happens: When trying to repair equipment, the xp cost for each repair keeps increasing.

What you expected to happen: If ignore_incremental_repair_cost is set to true, the xp cost should stay the same for each repair.

Steps to reproduce:

1. Shoot a normal bow a single time, and repair it multiple times.
2. 
3. 
...
____
Affected Versions (Do *not* use "latest"):

- Anvil Fix: 1.0.3
- Minecraft: 1.12.2
- Forge: 14.23.5.2768

**Comment by p455w0rd** [comment]
plase try this and report back on whether or not you still experience this: https://www.curseforge.com/minecraft/mc-mods/anvil-fix/files/2783775

**Comment by GrantGryczan** [comment]
I still experience this and I am using that version. I am merging a diamond sword with a sharpness I book repeatedly.
