### ISSUE TITLE
AnvilFix (1.12.2) is required on client

### ISSUE THREAD

**Issue by pkej** [NerdHubMC/AnvilFix#8]
#### Issue Description:
CurseForge page for AnvilFix states:

> Note: This mod is technically not needed on the client, but if not present the anvil GUI will show the "too expensive" warning instead of the level cost, even tho combining items will work.

#### What happens:

Trying to connect gets a connection denied, missing mod AnvilFix 1.0.3.

"Connection Lost

Server Mod rejections:
AnvilFix: Requires version 1.0.3 but mod is not found on client."

#### What you expected to happen:

Be able to connect without any problem.

#### Steps to reproduce:

1. Start a server with AnvilFix on it
2. Launch a Minecraft client witthout AnvilFix
3. Try to connect to the server with the client.
...

____
#### Affected Versions (Do *not* use "latest"):

- Anvil Fix:  1.0.3
- Minecraft: Minecraft 1.12.2
- Forge Loader: Forge 14.23.5.2838

#### Possibly Conflicting Mods (Provide their version, as well):
I ran both server and Minecraft with just Forge and AnvilFix enabled.

**Comment by UpcraftLP** [comment]
the 1.12 version was done by @p455w0rd, and is no longer being maintained. The description applies to the 1.14+ version ONLY.
