### ISSUE TITLE
Ignore incremental repair cost still not working properly

### ISSUE THREAD

**Issue by Dukeasas** [NerdHubMC/AnvilFix#9]
#### Issue Description: Ignore incremental repair cost still not working properly despise the new version. 
Note: If this bug occurs in a modpack, please report this to the modpack author. Otherwise, delete this line and add your description here. If this is a feature request, this template does not apply to you. Just delete everything.

#### What happens:
the repair cost keeps increasing exponentially 

#### What you expected to happen:
stop increasing

#### Steps to reproduce:

1. make a sword, hit once, and repair it.
2. do it again and again
3. 
...

____
#### Affected Versions (Do *not* use "latest"): 

- Anvil Fix: 1.0.5
- Minecraft: 1.12.2
- Fabric Loader: 
- Fabric API (if present): 

#### Possibly Conflicting Mods (Provide their version, as well):
- mod1 (1.0.0)
- mod2 (1.2.3.108)
- mod3 (1.14-1.3-123)

**Comment by UpcraftLP** [comment]
1.12 is no longer supported.
